---
1:
  type: 'bnn'
  input_network: [13, 6, 6]
  activation: ['ReLU'] #https://pytorch.org/docs/stable/nn.html#non-linear-activations-weighted-sum-nonlinearity
  optimizer: 'Adam'
  learning_rate: 0.001 
  weight_decay: 0.1
  loss_fn: 'CrossEntropyLoss' #https://neptune.ai/blog/pytorch-loss-functions for classification
  epochs: 1000
  batch_size: 64
# 2:
#   type: 'bnn'
#   input_network: [13, 6, 6]
#   activation: ['ReLU', 'ReLU'] #https://pytorch.org/docs/stable/nn.html#non-linear-activations-weighted-sum-nonlinearity
#   optimizer: 'Adam'
#   learning_rate: 0.01 
#   weight_decay: 0.1 
#   loss_fn: 'CrossEntropyLoss' #https://neptune.ai/blog/pytorch-loss-functions for classification
#   epochs: 1000
#   batch_size: 16

